// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCwOMQSBHYsbKU-sRmrOXlpDsniGmOQAI',
    appId: '1:105204797030:web:98aa9a42f2a29a9630a7a7',
    messagingSenderId: '105204797030',
    projectId: 'lazaapp-83019',
    authDomain: 'lazaapp-83019.firebaseapp.com',
    storageBucket: 'lazaapp-83019.appspot.com',
    measurementId: 'G-EMVMSVWZFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw9PsfzdrKBRc9eEUjNCVEibQvdnMlDIY',
    appId: '1:105204797030:android:68938260eb34c77530a7a7',
    messagingSenderId: '105204797030',
    projectId: 'lazaapp-83019',
    storageBucket: 'lazaapp-83019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEvcosH7EA0oVnAvCS_V0Ev3Vqr6meQj4',
    appId: '1:105204797030:ios:2d9e9497a60f4bea30a7a7',
    messagingSenderId: '105204797030',
    projectId: 'lazaapp-83019',
    storageBucket: 'lazaapp-83019.appspot.com',
    iosClientId: '105204797030-tu6t69f3i2dnifbaqdenu93pipu2rb1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerenceStoreUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEvcosH7EA0oVnAvCS_V0Ev3Vqr6meQj4',
    appId: '1:105204797030:ios:c9774a717c25aac630a7a7',
    messagingSenderId: '105204797030',
    projectId: 'lazaapp-83019',
    storageBucket: 'lazaapp-83019.appspot.com',
    iosClientId: '105204797030-4qchc0v3dittjae08mat0vo67ma8ahlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerenceStoreUi.RunnerTests',
  );
}
